#!/usr/bin/env bash
# parse-ref.sh — extract a PR reference from arbitrary input text and write
# a sourceable env file. Prints the env file path to stdout on success.
#
# Usage:
#   parse-ref.sh "<text containing a PR url or owner/repo#N>"
#
# Recognized forms (first match wins):
#   1. https?://github.com/OWNER/REPO/pull/N
#   2. github.com/OWNER/REPO/pull/N
#   3. OWNER/REPO#N
#
# Exit codes:
#   0  parsed; env file path on stdout
#   1  no recognizable PR reference found
#   2  usage error

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: parse-ref.sh <text>" >&2
  exit 2
fi

input="$*"

owner=""
repo=""
number=""

# 1. Full URL (with or without scheme)
if [[ "$input" =~ (https?://)?github\.com/([A-Za-z0-9._-]+)/([A-Za-z0-9._-]+)/pull/([0-9]+) ]]; then
  owner="${BASH_REMATCH[2]}"
  repo="${BASH_REMATCH[3]}"
  number="${BASH_REMATCH[4]}"
# 2. owner/repo#N
elif [[ "$input" =~ ([A-Za-z0-9._-]+)/([A-Za-z0-9._-]+)#([0-9]+) ]]; then
  owner="${BASH_REMATCH[1]}"
  repo="${BASH_REMATCH[2]}"
  number="${BASH_REMATCH[3]}"
else
  echo "parse-ref: no PR reference found in input" >&2
  echo "  accepted: https://github.com/OWNER/REPO/pull/N, github.com/OWNER/REPO/pull/N, OWNER/REPO#N" >&2
  exit 1
fi

project_slug="$(printf '%s' "$PWD" | sed 's|/|-|g')"
scratch_dir="${REVIEW_PR_SCRATCH_DIR:-$HOME/.claude/projects/${project_slug}/scratch}"
mkdir -p "$scratch_dir"

env_file="$scratch_dir/review-${owner}-${repo}-${number}.pr.env"
state_file="$scratch_dir/review-${owner}-${repo}-${number}.json"

cat > "$env_file" <<EOF
# Generated by parse-ref.sh
OWNER='$owner'
REPO='$repo'
NUMBER='$number'
REF='$owner/$repo#$number'
URL='https://github.com/$owner/$repo/pull/$number'
STATE_FILE='$state_file'
EOF

echo "$env_file"
